---
- name: Configuration templating
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Generate configuration files
    template: src=branch_office.j2 dest=CFGS/{{ item.hostname }}.txt
    with_items:
      - {hostname: pynet-rtr1, secret: <secret>, ip_addr: 10.10.10.20, netmask: 255.255.255.0,
          default_gateway: 10.10.10.1, access_vlan: 10, snmp_community: <community>,
          model_interfaces: 881_interfaces.j2, ckt_id: "Comcast #XXXX-227891"}
      - {hostname: pynet-rtr2, secret: <secret>, ip_addr: 10.10.20.20, netmask: 255.255.255.0,
          default_gateway: 10.10.20.1, access_vlan: 20, snmp_community: <community>,
          model_interfaces: 891_interfaces.j2, ckt_id: "AT&T #ZZZZ-897XR2"}
